### ISSUE TITLE
Format text box in Assignments

### ISSUE THREAD

**Issue by ChasonMindImp** [maltyeva/mindimp-pg#100]
What is the function of the format box in each assignment?

**Comment by maltyeva** [comment]
Good Question! When I made this, we haven't made assignments yet, so I added extra boxes, just in case. This is a text box now, but I can make it a selectbox for things like 500-word essay, 100-word response, etc, but depending on what the instructors want

**Comment by maltyeva** [comment]
Do people want me to keep this as a text-box, change it to something else, or to get rid of it?

**Comment by jzthompson** [comment]
I think leaving it as a text box is fine, as that is less restrictive. Personally I'm fine with keeping it, although I haven't used it in assignments so far. It might come in handy in the future.

**Comment by maltyeva** [comment]
ok! something that I think may help people is a 'hint' text box, like e.g.
'500-word' essay. Would that be something you guys would want?

**Comment by jzthompson** [comment]
Sure, that would be great.

**Comment by maltyeva** [comment]
ok, done!
