### ISSUE TITLE
Assignment Formatting Varies

### ISSUE THREAD

**Issue by ChasonMindImp** [maltyeva/mindimp-pg#104]
I attempted to add a little formatting to clean up the assignment I posted. The formatting appears to work here https://app.mindimp.com/course_assignments/24, but it does not work here https://app.mindimp.com/course_sessions/14

**Comment by maltyeva** [comment]
Thanks for pointing this out! I had only fixed it in that place. Could you check if it works similarly in the email that you get (you should get an instructor confirmation for assignments). 

Fixed and will be ready for the next push.

**Comment by ChasonMindImp** [comment]
I haven't received any of the assignment post emails, actually.

On Mon, Apr 27, 2015 at 5:15 PM, maltyeva <notifications@github.com> wrote:

> Thanks for pointing this out! I had only fixed it in that place. Could you
> check if it works similarly in the email that you get (you should get an
> instructor confirmation for assignments).
>
> Fixed and will be ready for the next push.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/104#issuecomment-96579573>.
>



-- 
Chason Dailey | 戴奇森
Program Manager and Advisor* | **思脉 **MindImp*
https://www.mindimp.com/

**Comment by jzthompson** [comment]
Yeah, same, I haven't been getting those notification emails either.
