### ISSUE TITLE
Expire course sessions

### ISSUE THREAD

**Issue by MindImpMatt** [maltyeva/mindimp-pg#109]
My finished US History course is still showing up under "My Courses" - could we have a way for courses to expire naturally (currently unless I missed something the only way to get rid of it is "Destroy Session")

**Comment by jzthompson** [comment]
Good point. There is a feature to mark a course as inactive. Could toggling this function be set so that it removes sessions from "My courses"?

**Comment by maltyeva** [comment]
yes, absolutely. I added the toggles, but haven't implemented them yet. I'm still finishing up the advisor code, but i'll add this and push it by today!

**Comment by maltyeva** [comment]
ok, added to next deploy. Make sure that the classes you are teaching are 'active' so the students can still see them
