### ISSUE TITLE
Course syllabus download links lead to random documents

### ISSUE THREAD

**Issue by jzthompson** [maltyeva/mindimp-pg#14]
...like Maria's W2 and Chason's health insurance form. I assume you're using these docs to just play around right now, but I thought I would ask to be sure. :)

**Comment by maltyeva** [comment]
Yes, sorry I was just testing the ability to upload PDFs with the only PDFs I had. We can upload any syllabi you have if you'd like :)

**Comment by jzthompson** [comment]
No syllabi yet, but I'll let you know when we have them!

**Comment by maltyeva** [comment]
this should be fixed as well!
