### ISSUE TITLE
Some Suggestions for Article details

### ISSUE THREAD

**Issue by MindImpMatt** [maltyeva/mindimp-pg#23]
-Date of publication
-Brief description
-Category (what's the word for this? Like, what section of the newspaper it would be in - politics/world news/arts/opinion/etc. Maybe subject?)
-Reading Level (currently our articles are divided into three groups, Levels 1-3, based on difficulty. Definitely should be included)
-Word count? Our book listings have pages, so I think a word count would be appropriate here.

**Comment by maltyeva** [comment]
Fixed. Will be on production with next deploy.
