### ISSUE TITLE
Articles refactoring

### ISSUE THREAD

**Issue by MindImpMatt** [maltyeva/mindimp-pg#24]
Based on source.

**Comment by maltyeva** [comment]
Changing this title. Since we're acquiring more articles and we're trying to get students more interested in the programs, I've refactored the way articles appear and added article sources. the changes should be live. 

@meagansiu & everyone else, i'd love to hear your feedback on how things look!

**Comment by meagansiu** [comment]
I think it looks cool! A couple little things I thought of right off the
bat:

1. Can we have the ability to destroy sources? I noticed that one was
accidentally added twice.

2. Can the banner at the top of the article list be randomized, so that it
shows different articles every time somebody visits the page? As our
article database gets bigger, I think the banner could be a good way for
students to discover an article that may get lost in all the content.

On Fri, Apr 24, 2015 at 10:01 AM, maltyeva <notifications@github.com> wrote:

> Changing this title. Since we're acquiring more articles and we're trying
> to get students more interested in the programs, I've refactored the way
> articles appear and added article sources. the changes should be live.
>
> @meagansiu <https://github.com/meagansiu> & everyone else, i'd love to
> hear your feedback on how things look!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/24#issuecomment-95773609>.
>



-- 
Meagan Siu, B.A. | 萧笑嫣
Program Manager and Advisor* | **思脉**MindImp *
http://www.mindimp.com.cn/
https://www.mindimp.com/

**Comment by maltyeva** [comment]
1. Yes, just added that and will be included in the next deploy. I keep on forgetting the destroy buttons :(

2. Yes, definitely possible! At the moment, these are hard-programmed in, because they rely on photos that aren't the article sources. For these banners, would you want the photos to be the same as an article source, or something different and related to the article itself? 
The pros of having article sources be the photos is that it would be more associated with the brand and we wouldn't have to upload a relevant photo (of a size that would make sense) to every article, but the cons would be that the page may look too generic. What do you guys think? 

Another thing that I wanted to ask was whether it still makes sense to keep the articles in the table as is to make them more like the books?

**Comment by ChasonMindImp** [comment]
If for the sake of consistency alone, I say keep the table. Perhaps one day
when we have neough students we can see how they are accessing the
information and streamline from there.

On Fri, Apr 24, 2015 at 10:25 AM, maltyeva <notifications@github.com> wrote:

>
>    1.
>
>    Yes, just added that and will be included in the next deploy. I keep
>    on forgetting the destroy buttons :(
>    2.
>
>    Yes, definitely possible! At the moment, these are hard-programmed in,
>    because they rely on photos that aren't the article sources. For these
>    banners, would you want the photos to be the same as an article source, or
>    something different and related to the article itself?
>    The pros of having article sources be the photos is that it would be
>    more associated with the brand and we wouldn't have to upload a relevant
>    photo (of a size that would make sense) to every article, but the cons
>    would be that the page may look too generic. What do you guys think?
>
> Another thing that I wanted to ask was whether it still makes sense to
> keep the articles in the table as is to make them more like the books?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/24#issuecomment-95778059>.
>



-- 
Chason Dailey | 戴奇森
Program Manager and Advisor* | **思脉 **MindImp*
https://www.mindimp.com/

**Comment by meagansiu** [comment]
Additional suggestions!

1. When looking at an article source page, add a button to the bottom that
allows the viewers to go back to the list of article sources.
2. I noticed that the URLs are just listed as text at the top of the page
for each source. Should we make them hyperlinks that will take the viewer
to the home page of the news website?

On Fri, Apr 24, 2015 at 10:36 AM, ChasonMindImp <notifications@github.com>
wrote:

> If for the sake of consistency alone, I say keep the table. Perhaps one day
> when we have neough students we can see how they are accessing the
> information and streamline from there.
>
> On Fri, Apr 24, 2015 at 10:25 AM, maltyeva <notifications@github.com>
> wrote:
>
> >
> > 1.
> >
> > Yes, just added that and will be included in the next deploy. I keep
> > on forgetting the destroy buttons :(
> > 2.
> >
> > Yes, definitely possible! At the moment, these are hard-programmed in,
> > because they rely on photos that aren't the article sources. For these
> > banners, would you want the photos to be the same as an article source,
> or
> > something different and related to the article itself?
> > The pros of having article sources be the photos is that it would be
> > more associated with the brand and we wouldn't have to upload a relevant
> > photo (of a size that would make sense) to every article, but the cons
> > would be that the page may look too generic. What do you guys think?
> >
> > Another thing that I wanted to ask was whether it still makes sense to
> > keep the articles in the table as is to make them more like the books?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/maltyeva/mindimp-pg/issues/24#issuecomment-95778059
> >.
> >
>
>
>
> --
> Chason Dailey | 戴奇森
> Program Manager and Advisor* | **思脉 **MindImp*
> https://www.mindimp.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/24#issuecomment-95779351>.
>



-- 
Meagan Siu, B.A. | 萧笑嫣
Program Manager and Advisor* | **思脉**MindImp *
http://www.mindimp.com.cn/
https://www.mindimp.com/

**Comment by maltyeva** [comment]
Both of those things are done! Will be pushed on the next update. :)

**Comment by maltyeva** [comment]
Closing this, since i addressed all the issues. let me know if anything else should be added!

**Comment by meagansiu** [comment]
Quick thing: when destroying a source, perhaps we should just destroy the
source itself and not all of the associated articles? I wouldn't want
somebody to destroy a source accidentally and then lose all of the
material. If a source is destroyed, could the articles just stay in the
database as "floaters" until somebody assigns them to a new source?

On Tue, Apr 28, 2015 at 12:07 PM, maltyeva <notifications@github.com> wrote:

> Closing this, since i addressed all the issues. let me know if anything
> else should be added!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/24#issuecomment-96904372>.
>



-- 
Meagan Siu, B.A. | 萧笑嫣
Program Manager and Advisor* | **思脉**MindImp *
http://www.mindimp.com.cn/
https://www.mindimp.com/

**Comment by maltyeva** [comment]
changed (but not yet live)
now, the association is nullified so all articles without sources will say
'no source'.

currently, articles need sources to be created, do you want me to lift that
limitation?

**Comment by meagansiu** [comment]
no, i think that should be fine :)

On Thu, Apr 30, 2015 at 11:31 AM, maltyeva <notifications@github.com> wrote:

> changed (but not yet live)
> now, the association is nullified so all articles without sources will say
> 'no source'.
>
> currently, articles need sources to be created, do you want me to lift that
> limitation?
>
> On Thu, Apr 30, 2015 at 9:56 AM meagansiu <notifications@github.com>
> wrote:
>
> > Quick thing: when destroying a source, perhaps we should just destroy the
> > source itself and not all of the associated articles? I wouldn't want
> > somebody to destroy a source accidentally and then lose all of the
> > material. If a source is destroyed, could the articles just stay in the
> > database as "floaters" until somebody assigns them to a new source?
> >
> > On Tue, Apr 28, 2015 at 12:07 PM, maltyeva <notifications@github.com>
> > wrote:
> >
> > > Closing this, since i addressed all the issues. let me know if anything
> > > else should be added!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/maltyeva/mindimp-pg/issues/24#issuecomment-96904372
> > >.
> > >
> >
> >
> >
> > --
> > Meagan Siu, B.A. | 萧笑嫣
> > Program Manager and Advisor* | **思脉**MindImp *
> > http://www.mindimp.com.cn/
> > https://www.mindimp.com/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/maltyeva/mindimp-pg/issues/24#issuecomment-97632880
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/24#issuecomment-97649497>.
>



-- 
Meagan Siu, B.A. | 萧笑嫣
Program Manager and Advisor* | **思脉**MindImp *
http://www.mindimp.com.cn/
https://www.mindimp.com/
