### ISSUE TITLE
Problems when editing Discussion questions

### ISSUE THREAD

**Issue by christine7hang** [maltyeva/mindimp-pg#25]
Hi Maria,
    I was putting info into discussion questions, but the order of the questions got messed up. Even when I type them in the right order, the questions for week 3 would pop up before questions for week 2. This happened with "I Know Why The Caged Bird Sings" and "Tuesdays with Morrie". The others that I did didn't have such problems. I'm confused why the order went wrong.

**Comment by maltyeva** [comment]
This is addressed in #71 so resolving this and merging
