### ISSUE TITLE
Should have an "Administrator portal home" button that allows one to return to portal from pages that can be visited from portal.

### ISSUE THREAD

**Issue by jzthompson** [maltyeva/mindimp-pg#4]
In the same way that for each book category, there is a "category home" button.

**Comment by maltyeva** [comment]
Hi Jeff, 

So there is actually a way to access the admin portal from every page from the NavBar, if you click on your name through a dropdown menu. But I realize this may not be the best solution if people don't see it. 

I think adding an admin portal page back button to these pages might introduce a lot of redundant code, but we should have a better way of displaying it. Perhaps we can add it to the top navigation bar if you are an administrator or add a special nav bar with the portal home? Additionally, we can do a sidebar that users can click on. What do you think?

**Comment by jzthompson** [comment]
Hey Maria,

Thanks for pointing that out. I'd missed that. I do like the idea of adding it to the top navigation bar for administrators. Also, for some reason, clicking on my name doesn't reliably open the dropdown menu. After some experimentation, I think I've found that it has something to do with whether or not I've clicked elsewhere on the website. Right after I open the website, I can open the dropdown menu as many times as I want. However, once I navigate elsewhere on the website (admin portal, contacts, about, etc.), the dropdown menu stops working. Returning to 'home' doesn't help - the menu still doesn't come up. I've tried this in Chrome on a Chromebook and a PC. Same results.

**Comment by maltyeva** [comment]
Thanks for pointing it out! It's actually a behaviour that's not on the production website but is on development so I'll need to run test deploys to fix it, and I'll take a look at it tonight, because I want to have a stable production environment during the day! I'll also add the Menu to the nav bar then.

**Comment by maltyeva** [comment]
This should be fixed with the side navbar :)
