### ISSUE TITLE
A page about Zoom

### ISSUE THREAD

**Issue by MindImpMatt** [maltyeva/mindimp-pg#42]
With some basic info, explain the features we use, link to the download, maybe a form to submit issues, etc.

**Comment by maltyeva** [comment]
Yes! Totally doable - could someone write out the info and I'll add it?

**Comment by maltyeva** [comment]
assigning to Matt for now, but we can collaborate on the doc.

**Comment by meagansiu** [comment]
We could also ask Iris for the instructions she has been sending out to students.

**Comment by ChasonMindImp** [comment]
Should these details be generally acceptable, or password-protected? I mainly ask because the tutorial features our designated meeting code.

**Comment by maltyeva** [comment]
Good point! Let's have these be generally viewable, but protect our info. 

Chason, could you get me another screenshot with a generic code number/generic name? :) thanks!

**Comment by maltyeva** [comment]
This should be closed. Finished yesterday :)
