### ISSUE TITLE
Could we add a column in the book list for lexile measure?

### ISSUE THREAD

**Issue by jzthompson** [maltyeva/mindimp-pg#45]

**Comment by maltyeva** [comment]
Yes! Do you mean in the table? Is this a column that you want just admins or both admins and students to see?

**Comment by jzthompson** [comment]
Yeah, I meant in the table. It could be visible to both students and admins. Thanks!

**Comment by maltyeva** [comment]
Added to the table! Will move to production in the next iteration.
