### ISSUE TITLE
The images in the far left column of the book list don't load for me.

### ISSUE THREAD

**Issue by jzthompson** [maltyeva/mindimp-pg#5]
I'm viewing with Chrome on a Chromebook.

**Comment by jzthompson** [comment]
Just a quick update: There are now five books on the list, and next to two of them (Fahrenheit 451 and Harry Potter), I can see an image of a book and the words "No image available". Next to the other three books, no image loads.

**Comment by maltyeva** [comment]
This should be fixed :)
