### ISSUE TITLE
Adding assignments leads to blank page

### ISSUE THREAD

**Issue by MindImpMatt** [maltyeva/mindimp-pg#53]
Whenever I add an assignment to the test course, I am redirected to a blank page (going back to the session page shows the assignments have still been added, though)

**Comment by maltyeva** [comment]
@MindImpMatt would you mind testing this again? I think it should do a different redirect? now. 
Change the assignee back to me once you can confirm/deny the issue! :)

**Comment by maltyeva** [comment]
@MindImpMatt would you mind taking a look at this? :)

**Comment by maltyeva** [comment]
This should be fixed. resolving.
