### ISSUE TITLE
Should we keep "View All Responses" for discussion questions?

### ISSUE THREAD

**Issue by MindImpMatt** [maltyeva/mindimp-pg#56]
Can a student choose to keep his responses hidden? Also won't this make it easier for students to copy others' answers - assuming its visible to any students before they respond to the question themselves.

**Comment by maltyeva** [comment]
Hey Matt, great question, so right now only admins can see the 'view responses button'. Would we want an option for students to see some responses?

Christine, can you double check that you can't see this as a student.

**Comment by jzthompson** [comment]
I think that allowing the instructor to show particularly good responses after an assignment has been turned in would be a good feature to have.

**Comment by maltyeva** [comment]
Good idea! Would you want this feature to be present just for class assignments or for book discussion questions as well?

**Comment by maltyeva** [comment]
@jzthompson pinging you for this issue :)

**Comment by jzthompson** [comment]
Oops, sorry I missed this. I think that the feature should just be used for class assignments, since in classes a number of students will complete an assignment at the same time.
