### ISSUE TITLE
visual fixes for article questions

### ISSUE THREAD

**Issue by meagansiu** [maltyeva/mindimp-pg#58]
just a visual improvement: delete "Week" and "chapter:" when looking at article questions, since they don't apply for articles

hard to explain what i mean, so i've included screenshot:

![screen shot 2015-03-24 at 12 51 22 pm](https://cloud.githubusercontent.com/assets/11342426/6795967/881be440-d224-11e4-89bf-bc6c9aa82f61.png)

**Comment by maltyeva** [comment]
Hey Meagan, this should be fixed. see if you like the look and let me know if anything else should be changed visually :)

**Comment by meagansiu** [comment]
I edited this question today and there appears to be the same problem :o unless the changes haven't been implemented yet?

![screen shot 2015-03-25 at 11 34 46 am](https://cloud.githubusercontent.com/assets/11342426/6817954/047ba598-d2e3-11e4-93f2-4316636acdcc.png)

**Comment by maltyeva** [comment]
ok, was able to fix it! Articles should now respond with a different layout and discussion questions can now be destroyed
