### ISSUE TITLE
Could we add the ability to add attachments like PDFs or Word docs to assignments?

### ISSUE THREAD

**Issue by jzthompson** [maltyeva/mindimp-pg#60]
Alternatively we could just add a repository of files in each course session, and students could download what they needed per the assignment instructions.

**Comment by jzthompson** [comment]
Some classes will also have jpeg files as parts of assignments.

**Comment by maltyeva** [comment]
Hey Jeff, 

Currently, assignment responses have attachments but I think that we can add those to the assignments as well. I'll bring this up as an  talking point at the meeting today to come up with a plan of attack. :)

**Comment by maltyeva** [comment]
Done and going on production soon.
