### ISSUE TITLE
Add Student Handbook to student dashboard...

### ISSUE THREAD

**Issue by ChasonMindImp** [maltyeva/mindimp-pg#61]
Or maybe on a general policy section to the website? However it is done, keeping this public and easily accessible will be helpful for students and useful for us if a parent or student ever tries to say they were unaware of something.

**Comment by maltyeva** [comment]
yes, could someone write this? Chason? :)

**Comment by ChasonMindImp** [comment]
Hey Maria,

There is a Student Handbook doc on Drive that we all reviewed.

Jeff, to confirm, is that the one you and/or Iris has been giving to
students?

**Comment by maltyeva** [comment]
@jzthompson mentioning jeff in case he didn't get a notification

**Comment by jzthompson** [comment]
The student handbook is pretty much what students are seeing. I made some
small edits to it and renamed it the "Student Responsibility Contract".
Students have to sign it when they register for MindImp programs. It's
attached here.

I get notifications every time someone posts in Github, but thanks for
making sure, Maria. :)

Best,

Jeff

**Comment by maltyeva** [comment]
Great! I actually can't see the attachment here on GitHub, would you mind sending it to me through email and I can add it to the site?

**Comment by maltyeva** [comment]
Ok, this is added to the navbar. WIll be live on next update.
