### ISSUE TITLE
Issues with assignments on the website

### ISSUE THREAD

**Issue by jzthompson** [maltyeva/mindimp-pg#65]
I just tried posting an assignment for the literature course. It posted, but once it did the website crashed. I refreshed the page, which caused the assignment to post a second time.

Also, it seems that there is no way to delete an assignment once it has been posted. I was hoping to delete one of my assignments since it's now double-posted.

Also, if I enter the "edit assignment" view and then click the back button to get out, I'm led to an error page.

Finally, I was wondering if I should be receiving email notifications when I post an assignment. I am listed as the instructor for the literature class, but I'm not listed as a student. It might be nice for instructors to get notification emails as well just so we know that the assignment has been sent out.

**Comment by maltyeva** [comment]
Hi Jeff, 

Thanks for the comments. 
- I fixed the link to destroy an assignment as well as the back button 
- there's a small issue that happens sometimes with emails having been sent, if the execution expires. let's keep an eye on those and see if we'll need to do an alternative. 
- As long as the assignemnt is created and you get a green 'created assignment and sent notification' notice, you should get an email, are you able to get those?

**Comment by jzthompson** [comment]
Thanks Maria. Clicking the 'back' button after I view or edit an assignment
still causes an error for me. Also, where is the "destroy" button for
assignments? I looked for it on the session page and on the edit assignment
page, but I couldn't find anything.
