### ISSUE TITLE
Privacy for student accounts

### ISSUE THREAD

**Issue by ChasonMindImp** [maltyeva/mindimp-pg#67]
I have not yet had students ask me about this (in part because I am still trying to get them to fill out their profiles), but is it possible (and worth doing) to add privacy settings for the profile? Specifically for contact information? Say, allow students to set if the information is either public (all MindImp admins and students) or just those in the same class/program/follow status, that sort of thing?

**Comment by maltyeva** [comment]
Good question! So currently, users who are just students can only see the biographical info (here's a screenshot from my student account looking at my non-student account). 

By default, they can't see each other's classes/books/articles/certifications, but we can change that. 

@ChasonMindImp @jzthompson @meagansiu @MindImpMatt  thoughts?

![screen shot 2015-04-01 at 3 34 03 pm](https://cloud.githubusercontent.com/assets/279604/6936440/decf51da-d884-11e4-9836-7e67166cb72d.png)

**Comment by ChasonMindImp** [comment]
Perhaps a toggle for contact information?

**Comment by maltyeva** [comment]
For other students?

**Comment by ChasonMindImp** [comment]
Exactly, though I am not sure how and when the information should or could be restricted. It could be attached to following (though if students can follow anyone than it really doesn't provide privacy), or what class you're in (though that wouldn't map with the reading program)...

**Comment by maltyeva** [comment]
What does everyone else think? I don't want to go as far as to create a
social network, but I'd like to hear people's thoughts on how information
will be displyed.

One thing that I do want to display on the site is a healthy amount of
competition -- coming soon with badges - because i hope it'll motivate
students.

**Comment by ChasonMindImp** [comment]
I love the badge idea. Definitely good. 

I know I am the one who raised the question, but barring any questions or complaints from students (none have yet come to me to say they haven't finished their profile for that reason), maybe shelf this for now until the concern is voiced?

**Comment by meagansiu** [comment]
I can't really think of a situation in which a student should need to know
another student's contact info, as none of our programs require out of
class partner or group work. Personally, I think it's okay if all contact
info is hidden from students.

**Comment by maltyeva** [comment]
ok. resolving.
