### ISSUE TITLE
order of discussion questions after editing

### ISSUE THREAD

**Issue by meagansiu** [maltyeva/mindimp-pg#71]
it would be helpful if, after editing a discussion question, it would stay in the same place in the list instead of going to the end of all the discussion questions

**Comment by maltyeva** [comment]
I can't replicate this behaviour. Would you mind sending a screenshot? :)

**Comment by meagansiu** [comment]
Week 2&3 questions mixed together in "I Know Why the Caged Bird Sings":
![screen shot 2015-04-01 at 4 25 44 pm](https://cloud.githubusercontent.com/assets/11342426/6937165/fabe754a-d88b-11e4-9183-d4258acabf8d.png)

There is another example in Chapters 1&2 in Tuesdays With Morrie. This also occurs occasionally when adding new discussion questions, but I can never really replicate that consistently either.

**Comment by meagansiu** [comment]
Sorry, I realize this is an example of questions going into a random spot. Yesterday, all the edited questions seemed to go to the end of the list.

**Comment by maltyeva** [comment]
okay, that makes sense! I can have the list of questions sort by created, or would you want it to be sorted based on an arbitrary id that you assign it?

**Comment by meagansiu** [comment]
Would having the sorting based on an arbitrary id allow us to play around
with the order of questions later on? I'm thinking that once we have more
experience working with students on specific books, we might want to add
questions to certain chapters in the middle of the book, edit the phrasing
of questions (and have the questions stay in the same place in the list),
etc.

**Comment by maltyeva** [comment]
Yeah, it would. The only issue would be back-ordering the currently added
questions, but I think we can make an intern do it, if necessary

**Comment by meagansiu** [comment]
update: in terms of adding questions at least, the problem seems to be more persistent after four questions or so

**Comment by maltyeva** [comment]
Ok, I modified the week field that's there for books to work as a sorting algorithm for articles and added sorting as well. Keeping this open because i didn't edit books yet, since i want to see if this method is convenient for articles.

**Comment by maltyeva** [comment]
edited this with books as well, so resolving!
