### ISSUE TITLE
Course packets cannot be edited without adding new attachments

### ISSUE THREAD

**Issue by jzthompson** [maltyeva/mindimp-pg#81]
Editing a course packet requires adding a new attachment and description. If I don't add a new attachment but try to make other changes (e.g., changing a previous document description or changing the name of the course packet), I get an error message and the changes I made are not applied.

I also don't see a way to delete a previously attached file from a course packet without  adding a new one.

**Comment by maltyeva** [comment]
This was fixed in an earlier bug. Let me know if there are still issues :)

**Comment by jzthompson** [comment]
There still seems to be an issue. I can now edit course packets without adding an attachment, but doing so still adds a blank "item" to the list of items in the course packet. I edited one item on the US History course packet, and then edited it again to change it back. Here is how it now looks, with two blank items added:

![us history course packet problem](https://cloud.githubusercontent.com/assets/10520630/7231755/4f9b50a2-e745-11e4-9638-9da669f64777.PNG)

The editing also moved the course packets out of the order they'd been in, which makes them look a little messy. Could there be a way to manually order the items?

Also, I was thinking that there should be a way to delete or destroy an item in a course packet as well. I couldn't find a way to do that either.
