### ISSUE TITLE
"back to responses" button after giving comments on student response

### ISSUE THREAD

**Issue by meagansiu** [maltyeva/mindimp-pg#83]
I think it would be helpful if the "back to responses" button took us back to all the responses the student has completed for a particular article, instead of taking us to all the responses all students have completed for one individual question in one article. 

(picture below, to clarify which specific link I'm talking about):
![screen shot 2015-04-07 at 10 04 27 am](https://cloud.githubusercontent.com/assets/11342426/7015897/dd34c67e-dd0d-11e4-9f1d-da36a197ef1c.png)

**Comment by maltyeva** [comment]
Fixed. Should be ready on next deploy! 

Example here: 

![screen shot 2015-04-10 at 4 19 26 pm](https://cloud.githubusercontent.com/assets/279604/7084220/6c40809c-df9d-11e4-8f4d-1ed399b6eef7.png)
