### ISSUE TITLE
Read Article Link Should Open New Window

### ISSUE THREAD

**Issue by ChasonMindImp** [maltyeva/mindimp-pg#87]
Instead of navigating the user completely away from the website. 

(Low Priority) In the future, would it be possible maintain a MindImp nav bar over the article page as well? There could be options to return to the article or to even access questions as one reads.

**Comment by maltyeva** [comment]
Added to the site to open in a new tab (like the download link), will push on the next upload!

Re: the navigation bar, the thing is that now the article currently takes you away to the site itself, the only way to keep a mindimp presence would be to embed the article within our site, which is possible, but it's clunky (think PDF menus embeded in a website). What do you guys think?

**Comment by ChasonMindImp** [comment]
I see. It is definitely not a necessity, but I am curious to see what
people think as well.

On Wed, Apr 15, 2015 at 3:00 PM, maltyeva <notifications@github.com> wrote:

> Added to the site to open in a new tab (like the download link), will push
> on the next upload!
>
> Re: the navigation bar, the thing is that now the article currently takes
> you away to the site itself, the only way to keep a mindimp presence would
> be to embed the article within our site, which is possible, but it's clunky
> (think PDF menus embeded in a website). What do you guys think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/87#issuecomment-93225054>.
>



-- 
Chason Dailey | 戴奇森
Program Manager and Advisor* | MindImp 思脉*
https://www.mindimp.com/
https://app.mindimp.com/

**Comment by jzthompson** [comment]
I think that that the nav bar would be nice, but maybe unnecessary if it isn't easy to do. At least with how it works now you automatically have one tab with the questions and another tab with the article when you download an article.

**Comment by maltyeva** [comment]
ok, in that case, resolving. This should now be live
