### ISSUE TITLE
Formatting for Course Assignments

### ISSUE THREAD

**Issue by MindImpMatt** [maltyeva/mindimp-pg#92]
I've been trying out adding an assignment to my course in Global Perspectives, one which has a couple links and descriptions. 

https://app.mindimp.com/course_assignments/16

I can't figure out how to format it so the paragraphs remain intact and separate (especially the different links) - @maltyeva am I doing something wrong / should I instead create a course packet and refer students to that?

**Comment by MindImpMatt** [comment]
(closed out that assignment since I added a course packet instead, but basically the assignment was created as a block of text even though I had paragraphs/separate links in the assignment creation form - could just be my mistake though)

**Comment by maltyeva** [comment]
Hey Matt!

This is now fixed and will be pushed with the changes tonight. If there are any other areas where you'd like to have the line separation be done (discussion questions?), let me know!
