### ISSUE TITLE
Destroying an assignment redirects to course session list

### ISSUE THREAD

**Issue by ChasonMindImp** [maltyeva/mindimp-pg#99]
[https://app.mindimp.com/course_sessions] Rather than back to the course itself

**Comment by maltyeva** [comment]
Fixed this and will be present on the next push! 

I put the delete button more prominently as well. The issue before was that when the assignment was destroyed, it also destroyed the association and as a result it didn't know where to return to. The new destroy link should keep you on the course page :)

**Comment by ChasonMindImp** [comment]
Thank  you :)

On Mon, Apr 27, 2015 at 1:42 PM, maltyeva <notifications@github.com> wrote:

> Fixed this and will be present on the next push!
>
> I put the delete button more prominently as well. The issue before was
> that when the assignment was destroyed, it also destroyed the association
> and as a result it didn't know where to return to. The new destroy link
> should keep you on the course page :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/99#issuecomment-96513314>.
>



-- 
Chason Dailey | 戴奇森
Program Manager and Advisor* | **思脉 **MindImp*
https://www.mindimp.com/
